
# keeping the lights-on specs
exclude:
  - Gemfile
  - Gemfile.lock
baseurl: ""
timezone: America/New_York
future: TRUE

# blog related ish
gems: [jekyll-paginate, kramdown 2.3.1, rouge]
excerpt_separator: <!–break–>
paginate: 5
paginate_path: "read/page:num"
markdown: kramdown
kramdown: 
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
